export type SourcebookSpellFormulaStatus =
  | "not-started"
  | "needs-review"
  | "verified";

export interface SourcebookSpellReference {
  id: string;
  name: string;
  level: number;
  school: string;
  classes: string[];
  castingTime: string;
  range: string;
  components: string;
  duration: string;
  sourcebookId: string;
  sourceUrl: string;
  formulaStatus: SourcebookSpellFormulaStatus;
}

const valdasSourcebookId = "valdas-spire-of-secrets-player-pack-2";
const valdasSourceUrl =
  "https://www.dndbeyond.com/sources/dnd/vsspp2/valdas-spire-of-secrets-player-pack-2#Spells";

/** Book-index metadata only; spell rules are interpreted in the manual formula files. */
const sourcebookSpells: SourcebookSpellReference[] = [
  {
    id: "arc_blade",
    name: "Arc Blade",
    level: 0,
    school: "evocation",
    classes: ["sorcerer", "warlock", "wizard"],
    castingTime: "1 action",
    range: "15 ft.",
    components: "S, M (proficient melee weapon worth 1+ CP)",
    duration: "Instantaneous",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "needs-review",
  },
  {
    id: "blunder",
    name: "Blunder",
    level: 2,
    school: "enchantment",
    classes: ["bard", "wizard"],
    castingTime: "1 reaction",
    range: "30 ft.",
    components: "S, M (a banana peel)",
    duration: "Instantaneous",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "burning_blade",
    name: "Burning Blade",
    level: 0,
    school: "evocation",
    classes: ["sorcerer", "warlock", "wizard"],
    castingTime: "1 action",
    range: "Self",
    components: "S, M (proficient melee weapon worth 1+ CP)",
    duration: "Instantaneous",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "candy_blast",
    name: "Candy Blast",
    level: 0,
    school: "conjuration",
    classes: ["sorcerer", "wizard"],
    castingTime: "1 action",
    range: "60 ft.",
    components: "V, S",
    duration: "Instantaneous",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "cheat",
    name: "Cheat",
    level: 0,
    school: "divination",
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    castingTime: "1 bonus action",
    range: "Self",
    components: "S, M (a weighted die)",
    duration: "1 round",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "cosmic_horror",
    name: "Cosmic Horror",
    level: 3,
    school: "conjuration",
    classes: ["sorcerer", "warlock", "wizard"],
    castingTime: "1 action",
    range: "60 ft.",
    components: "V, S, M (a dream journal)",
    duration: "Concentration, up to 1 minute",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "flashback",
    name: "Flashback",
    level: 3,
    school: "divination",
    classes: ["bard", "cleric", "wizard"],
    castingTime: "1 action",
    range: "Self",
    components: "V, S",
    duration: "Instantaneous",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "flawed_reconstruction",
    name: "Flawed Reconstruction",
    level: 1,
    school: "transmutation",
    classes: ["sorcerer", "warlock", "wizard"],
    castingTime: "1 action",
    range: "Touch",
    components: "V, S, M (needle and thread)",
    duration: "Instantaneous",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "frenzy",
    name: "Frenzy",
    level: 6,
    school: "enchantment",
    classes: ["bard", "wizard"],
    castingTime: "1 action",
    range: "120 ft.",
    components: "V, S, M (a drop of fresh blood)",
    duration: "Concentration, up to 1 minute",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "frigid_blade",
    name: "Frigid Blade",
    level: 0,
    school: "evocation",
    classes: ["sorcerer", "warlock", "wizard"],
    castingTime: "1 action",
    range: "Self",
    components: "S, M (proficient melee weapon worth 1+ CP)",
    duration: "Instantaneous",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "needs-review",
  },
  {
    id: "mandys_marvelous_dress",
    name: "Mandy’s Marvelous Dress",
    level: 4,
    school: "conjuration",
    classes: ["bard"],
    castingTime: "1 action",
    range: "Touch",
    components: "V, S, M (glass slipper worth 100+ GP)",
    duration: "Concentration, special",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "protect_threshold",
    name: "Protect Threshold",
    level: 2,
    school: "abjuration",
    classes: ["sorcerer", "wizard"],
    castingTime: "1 action or ritual",
    range: "Touch",
    components: "V, S, M (salt; 1 oz. per foot of portal perimeter)",
    duration: "10 minutes",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "rocks_fall",
    name: "Rocks Fall",
    level: 8,
    school: "conjuration",
    classes: ["druid", "sorcerer", "warlock", "wizard"],
    castingTime: "1 action",
    range: "120 ft.",
    components: "V, S, M (ten dice)",
    duration: "Instantaneous",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "rusting_grasp",
    name: "Rusting Grasp",
    level: 3,
    school: "transmutation",
    classes: ["druid", "sorcerer", "wizard"],
    castingTime: "1 action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "seance",
    name: "Séance",
    level: 3,
    school: "necromancy",
    classes: ["bard", "wizard"],
    castingTime: "10 minutes",
    range: "Self",
    components: "V, S, M (focus and incense worth 50+ GP)",
    duration: "1 minute",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "soul_effigy",
    name: "Soul Effigy",
    level: 4,
    school: "necromancy",
    classes: ["warlock"],
    castingTime: "1 minute or ritual",
    range: "Touch",
    components: "V, S, M (straw doll worth 1+ CP)",
    duration: "8 hours",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "stone_bones",
    name: "Stone Bones",
    level: 2,
    school: "transmutation",
    classes: ["druid", "paladin", "ranger", "sorcerer", "wizard"],
    castingTime: "1 bonus action",
    range: "30 ft.",
    components: "V, S",
    duration: "1 round",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "swift_flight",
    name: "Swift Flight",
    level: 2,
    school: "transmutation",
    classes: ["sorcerer", "wizard"],
    castingTime: "1 bonus action",
    range: "Touch",
    components: "V, S, M (a bird’s wing feather)",
    duration: "1 round",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "sword_of_judgment",
    name: "Sword of Judgment",
    level: 5,
    school: "conjuration",
    classes: ["cleric", "paladin"],
    castingTime: "1 action",
    range: "60 ft.",
    components: "V, S, M (a strand of horse hair)",
    duration: "Concentration, up to 1 minute",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "transient_bulwark",
    name: "Transient Bulwark",
    level: 1,
    school: "abjuration",
    classes: ["sorcerer", "wizard"],
    castingTime: "1 action or ritual",
    range: "Self",
    components: "V, S, M (consumed pearl worth 10+ GP)",
    duration: "8 hours",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
  {
    id: "zephyrs_feather",
    name: "Zephyr’s Feather",
    level: 1,
    school: "conjuration",
    classes: ["druid", "ranger", "sorcerer", "warlock", "wizard"],
    castingTime: "1 action",
    range: "Self",
    components: "V, S, M (a dove’s feather)",
    duration: "Concentration, up to 1 minute",
    sourcebookId: valdasSourcebookId,
    sourceUrl: valdasSourceUrl,
    formulaStatus: "not-started",
  },
];

export const DND_SOURCEBOOK_SPELLS = sourcebookSpells.map((spell) => ({
  ...spell,
  formulaStatus: "needs-review" as const,
}));
