export interface DndBackgroundDefinition {
    id: string;
    name: string;
    sourcebookId: string;
    source: string;
    abilityScores: Array<"STR" | "DEX" | "CON" | "INT" | "WIS" | "CHA">;
    featId: string;
    featName: string;
    skills: string[];
    tool: string;
}

export const PHB_2024_BACKGROUNDS: Record<string, DndBackgroundDefinition> = {
    acolyte: { id: "acolyte", name: "Acolyte", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["INT", "WIS", "CHA"], featId: "feat:magic-initiate-cleric", featName: "Magic Initiate (Cleric)", skills: ["Insight", "Religion"], tool: "Calligrapher’s Supplies" },
    artisan: { id: "artisan", name: "Artisan", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["STR", "DEX", "INT"], featId: "feat:crafter", featName: "Crafter", skills: ["Investigation", "Persuasion"], tool: "Artisan’s Tools" },
    charlatan: { id: "charlatan", name: "Charlatan", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["DEX", "CON", "CHA"], featId: "feat:skilled", featName: "Skilled", skills: ["Deception", "Sleight of Hand"], tool: "Forgery Kit" },
    criminal: { id: "criminal", name: "Criminal", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["DEX", "CON", "INT"], featId: "feat:alert", featName: "Alert", skills: ["Deception", "Stealth"], tool: "Thieves’ Tools" },
    entertainer: { id: "entertainer", name: "Entertainer", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["STR", "DEX", "CHA"], featId: "feat:musician", featName: "Musician", skills: ["Acrobatics", "Performance"], tool: "Musical Instrument" },
    farmer: { id: "farmer", name: "Farmer", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["STR", "CON", "WIS"], featId: "feat:tough", featName: "Tough", skills: ["Animal Handling", "Nature"], tool: "Carpenter’s Tools" },
    guard: { id: "guard", name: "Guard", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["STR", "INT", "WIS"], featId: "feat:alert", featName: "Alert", skills: ["Athletics", "Perception"], tool: "Gaming Set" },
    guide: { id: "guide", name: "Guide", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["DEX", "CON", "WIS"], featId: "feat:magic-initiate-druid", featName: "Magic Initiate (Druid)", skills: ["Stealth", "Survival"], tool: "Cartographer’s Tools" },
    hermit: { id: "hermit", name: "Hermit", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["CON", "WIS", "CHA"], featId: "feat:healer", featName: "Healer", skills: ["Medicine", "Religion"], tool: "Herbalism Kit" },
    merchant: { id: "merchant", name: "Merchant", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["CON", "INT", "CHA"], featId: "feat:lucky", featName: "Lucky", skills: ["Animal Handling", "Persuasion"], tool: "Navigator’s Tools" },
    noble: { id: "noble", name: "Noble", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["STR", "INT", "CHA"], featId: "feat:skilled", featName: "Skilled", skills: ["History", "Persuasion"], tool: "Gaming Set" },
    sage: { id: "sage", name: "Sage", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["CON", "INT", "WIS"], featId: "feat:magic-initiate-wizard", featName: "Magic Initiate (Wizard)", skills: ["Arcana", "History"], tool: "Calligrapher’s Supplies" },
    sailor: { id: "sailor", name: "Sailor", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["STR", "DEX", "WIS"], featId: "feat:tavern-brawler", featName: "Tavern Brawler", skills: ["Acrobatics", "Perception"], tool: "Navigator’s Tools" },
    scribe: { id: "scribe", name: "Scribe", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["DEX", "INT", "WIS"], featId: "feat:skilled", featName: "Skilled", skills: ["Investigation", "Perception"], tool: "Calligrapher’s Supplies" },
    soldier: { id: "soldier", name: "Soldier", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["STR", "DEX", "CON"], featId: "feat:savage-attacker", featName: "Savage Attacker", skills: ["Athletics", "Intimidation"], tool: "Gaming Set" },
    wayfarer: { id: "wayfarer", name: "Wayfarer", sourcebookId: "phb-2024", source: "Player's Handbook (2024)", abilityScores: ["DEX", "WIS", "CHA"], featId: "feat:lucky", featName: "Lucky", skills: ["Insight", "Stealth"], tool: "Thieves’ Tools" },
};

export const GRIM_HOLLOW_BACKGROUNDS: Record<string, DndBackgroundDefinition> = {
    agent_of_the_augustine: { id: "agent_of_the_augustine", name: "Agent of the Augustine", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["INT", "WIS", "CHA"], featId: "feat:insightful-collector", featName: "Insightful Collector", skills: ["History", "Persuasion"], tool: "Forgery Kit" },
    antiquarian: { id: "antiquarian", name: "Antiquarian", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["DEX", "CON", "INT"], featId: "feat:skilled", featName: "Skilled", skills: ["Arcana", "History"], tool: "Tinker’s Tools" },
    beast_hunter: { id: "beast_hunter", name: "Beast Hunter", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["STR", "DEX", "INT"], featId: "feat:blood-hound", featName: "Blood Hound", skills: ["Animal Handling", "Survival"], tool: "Leatherworker’s Tools" },
    beggar: { id: "beggar", name: "Beggar", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["STR", "DEX", "WIS"], featId: "feat:survivor", featName: "Survivor", skills: ["Insight", "Persuasion"], tool: "Disguise Kit" },
    chapter_knight: { id: "chapter_knight", name: "Chapter Knight", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["STR", "WIS", "CHA"], featId: "feat:savage-attacker", featName: "Savage Attacker", skills: ["Animal Handling", "Athletics"], tool: "Musical Instrument" },
    courtier: { id: "courtier", name: "Courtier", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["INT", "WIS", "CHA"], featId: "feat:skilled", featName: "Skilled", skills: ["Insight", "Persuasion"], tool: "Artisan’s Tools" },
    disgraced_raider: { id: "disgraced_raider", name: "Disgraced Raider", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["STR", "CON", "WIS"], featId: "feat:savage-attacker", featName: "Savage Attacker", skills: ["Athletics", "Nature"], tool: "Navigator’s Tools" },
    envoy: { id: "envoy", name: "Envoy", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["STR", "CON", "CHA"], featId: "feat:skilled", featName: "Skilled", skills: ["Insight", "Persuasion"], tool: "Calligrapher’s Supplies" },
    executioner: { id: "executioner", name: "Executioner", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["STR", "CON", "INT"], featId: "feat:deathbound", featName: "Deathbound", skills: ["Athletics", "Medicine"], tool: "Smith’s Tools" },
    explorer: { id: "explorer", name: "Explorer", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["STR", "CON", "WIS"], featId: "feat:alert", featName: "Alert", skills: ["Athletics", "Survival"], tool: "Navigator’s Tools" },
    exterminator: { id: "exterminator", name: "Exterminator", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["DEX", "CON", "INT"], featId: "feat:magic-initiate-druid", featName: "Magic Initiate (Druid)", skills: ["Animal Handling", "Medicine"], tool: "Poisoner’s Kit" },
    fey_blessed: { id: "fey_blessed", name: "Fey-Blessed", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["DEX", "CON", "CHA"], featId: "feat:magic-initiate-wizard", featName: "Magic Initiate (Wizard)", skills: ["Arcana", "Performance"], tool: "Musical Instrument" },
    free_swords_mercenary: { id: "free_swords_mercenary", name: "Free Swords Mercenary", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["STR", "DEX", "CON"], featId: "feat:free-sword-will", featName: "Free Sword Mercenary’s Will", skills: ["Acrobatics", "Athletics"], tool: "Gaming Set" },
    heretic: { id: "heretic", name: "Heretic", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["STR", "DEX", "WIS"], featId: "feat:magic-initiate-cleric", featName: "Magic Initiate (Cleric)", skills: ["Deception", "Religion"], tool: "Disguise Kit" },
    inquisitor_of_the_faithful: { id: "inquisitor_of_the_faithful", name: "Inquisitor of the Faithful", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["STR", "WIS", "CHA"], featId: "feat:convincing-inquisitor", featName: "Convincing Inquisitor", skills: ["Intimidation", "Religion"], tool: "Navigator’s Tools" },
    lapsed_inquisitor: { id: "lapsed_inquisitor", name: "Lapsed Inquisitor", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["STR", "WIS", "CHA"], featId: "feat:convincing-inquisitor", featName: "Convincing Inquisitor", skills: ["Persuasion", "Religion"], tool: "Navigator’s Tools" },
    one_of_the_taken: { id: "one_of_the_taken", name: "One of the Taken", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["DEX", "WIS", "CHA"], featId: "feat:magic-initiate-druid", featName: "Magic Initiate (Druid)", skills: ["Arcana", "Nature"], tool: "Woodcarver’s Tools" },
    physician: { id: "physician", name: "Physician", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["DEX", "INT", "WIS"], featId: "feat:triage-expert", featName: "Triage Expert", skills: ["Medicine", "Nature"], tool: "Herbalism Kit" },
    pioneer: { id: "pioneer", name: "Pioneer", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["STR", "CON", "WIS"], featId: "feat:survivor", featName: "Survivor", skills: ["Athletics", "Survival"], tool: "Carpenter’s Tools" },
    pit_fighter: { id: "pit_fighter", name: "Pit Fighter", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["STR", "DEX", "CHA"], featId: "feat:savage-attacker", featName: "Savage Attacker", skills: ["Athletics", "Performance"], tool: "Gaming Set" },
    pox_touched: { id: "pox_touched", name: "Pox-Touched", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["CON", "INT", "WIS"], featId: "feat:triage-expert", featName: "Triage Expert", skills: ["Intimidation", "Medicine"], tool: "Herbalism Kit" },
    prisoner: { id: "prisoner", name: "Prisoner", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["DEX", "CON", "CHA"], featId: "feat:alert", featName: "Alert", skills: ["Deception", "Sleight of Hand"], tool: "Thieves’ Tools" },
    released_thrall: { id: "released_thrall", name: "Released Thrall", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["CON", "INT", "WIS"], featId: "feat:survivor", featName: "Survivor", skills: ["Perception", "Stealth"], tool: "Artisan’s Tools" },
    scion_of_the_thaumaturge: { id: "scion_of_the_thaumaturge", name: "Scion of the Thaumaturge", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["INT", "WIS", "CHA"], featId: "feat:fortune-of-the-thaumaturge", featName: "Fortune of the Thaumaturge", skills: ["Arcana", "Insight"], tool: "Cartographer’s Tools" },
    syndicate_smuggler: { id: "syndicate_smuggler", name: "Syndicate Smuggler", sourcebookId: "grim-hollow-players-guide", source: "Grim Hollow: Player’s Guide", abilityScores: ["DEX", "INT", "CHA"], featId: "feat:resolution-of-the-syndicate", featName: "Resolution of the Syndicate", skills: ["History", "Stealth"], tool: "Forgery Kit" },
};

export const ARCANA_UNLEASHED_BACKGROUNDS: Record<string, DndBackgroundDefinition> = {
    agent_of_the_ninth_quill: { id: "agent_of_the_ninth_quill", name: "Agent of the Ninth Quill", sourcebookId: "arcana-unleashed", source: "Arcana Unleashed", abilityScores: ["DEX", "INT", "CHA"], featId: "feat:arcane-infiltrator", featName: "Arcane Infiltrator", skills: ["Arcana", "Sleight of Hand"], tool: "Thieves’ Tools" },
    bejeweled_conclave_spy: { id: "bejeweled_conclave_spy", name: "Bejeweled Conclave Spy", sourcebookId: "arcana-unleashed", source: "Arcana Unleashed", abilityScores: ["DEX", "WIS", "CHA"], featId: "feat:arcane-eloquence", featName: "Arcane Eloquence", skills: ["Deception", "Perception"], tool: "Disguise Kit" },
    cosmic_dawn_experiment: { id: "cosmic_dawn_experiment", name: "Cosmic Dawn Experiment", sourcebookId: "arcana-unleashed", source: "Arcana Unleashed", abilityScores: ["STR", "DEX", "CON"], featId: "feat:transmuted-anatomy", featName: "Transmuted Anatomy", skills: ["Athletics", "Survival"], tool: "Artisan’s Tools" },
    covenant_of_the_grave_recruit: { id: "covenant_of_the_grave_recruit", name: "Covenant of the Grave Recruit", sourcebookId: "arcana-unleashed", source: "Arcana Unleashed", abilityScores: ["STR", "INT", "WIS"], featId: "feat:arcane-undertaker", featName: "Arcane Undertaker", skills: ["History", "Medicine"], tool: "Herbalism Kit" },
    crucible_storm_chaser: { id: "crucible_storm_chaser", name: "Crucible Storm Chaser", sourcebookId: "arcana-unleashed", source: "Arcana Unleashed", abilityScores: ["STR", "CON", "INT"], featId: "feat:arcane-overload", featName: "Arcane Overload", skills: ["Athletics", "Nature"], tool: "Glassblower’s Tools" },
    familiar_trainer: { id: "familiar_trainer", name: "Familiar Trainer", sourcebookId: "arcana-unleashed", source: "Arcana Unleashed", abilityScores: ["CON", "INT", "WIS"], featId: "feat:familiar-friend", featName: "Familiar Friend", skills: ["Animal Handling", "Arcana"], tool: "Gaming Set" },
    horizon_weaver_initiate: { id: "horizon_weaver_initiate", name: "Horizon Weaver Initiate", sourcebookId: "arcana-unleashed", source: "Arcana Unleashed", abilityScores: ["DEX", "CON", "WIS"], featId: "feat:portal-jumper", featName: "Portal Jumper", skills: ["Acrobatics", "Survival"], tool: "Weaver’s Tools" },
    phantasmic_circus_trouper: { id: "phantasmic_circus_trouper", name: "Phantasmic Circus Trouper", sourcebookId: "arcana-unleashed", source: "Arcana Unleashed", abilityScores: ["DEX", "CON", "CHA"], featId: "feat:arcane-artist", featName: "Arcane Artist", skills: ["Deception", "Performance"], tool: "Disguise Kit" },
    seer_apprentice: { id: "seer_apprentice", name: "Seer Apprentice", sourcebookId: "arcana-unleashed", source: "Arcana Unleashed", abilityScores: ["INT", "WIS", "CHA"], featId: "feat:arcane-omens", featName: "Arcane Omens", skills: ["History", "Insight"], tool: "Navigator’s Tools" },
    ward_of_the_sheltering_hands: { id: "ward_of_the_sheltering_hands", name: "Ward of the Sheltering Hands", sourcebookId: "arcana-unleashed", source: "Arcana Unleashed", abilityScores: ["CON", "WIS", "CHA"], featId: "feat:arcane-safeguard", featName: "Arcane Safeguard", skills: ["Insight", "Medicine"], tool: "Cook’s Utensils" },
};

export const ALL_BACKGROUNDS: Record<string, DndBackgroundDefinition> = {
    ...PHB_2024_BACKGROUNDS,
    ...GRIM_HOLLOW_BACKGROUNDS,
    ...ARCANA_UNLEASHED_BACKGROUNDS,
};
